# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79fe651f30ab0986ca9f3c7e74125f675a7133d878ec156c1ee12ce4eb6952a60f5a6552f61878d5494b634755ffe438715bb2d6836333b0c37e8e788400c2ad

test:
  secret_key_base: 02fb9d2214219183bd3ac1d13867d2331befbdb68aa36ab2b051445e23b1ee5c5e3e29b791f9776b8f9cc230fb2ac124392eaf282fa3c24bf29c75dc03371eb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
